import { Table, Thead, Tbody, Tr, Th, Td } from "@chakra-ui/react";
import React from "react";

import ContentsContainer from "../common/ContentsContainer";
import H2 from "../common/h2";

const SkillStacks = () => {
  return (
    <ContentsContainer>
      <H2 id="skill-stack">スキルスタック</H2>
      <Table variant="simple" size="sm">
        <Thead>
          <Tr>
            <Th>スキル</Th>
            <Th>カテゴリ</Th>
            <Th>熟練度</Th>
          </Tr>
        </Thead>
        <Tbody>
          <Tr>
            <Td>PHP</Td>
            <Td>言語</Td>
            <Td>業務で利用した</Td>
          </Tr>
          <Tr>
            <Td>TypeScript</Td>
            <Td>言語</Td>
            <Td>業務で利用した</Td>
          </Tr>
          <Tr>
            <Td>JavaScript</Td>
            <Td>言語</Td>
            <Td>業務で利用した</Td>
          </Tr>
          <Tr>
            <Td>Java</Td>
            <Td>言語</Td>
            <Td>業務で利用した</Td>
          </Tr>
          <Tr>
            <Td>GAS</Td>
            <Td>言語</Td>
            <Td>業務で利用した</Td>
          </Tr>
          <Tr>
            <Td>HTML</Td>
            <Td>言語</Td>
            <Td>業務で利用した</Td>
          </Tr>
          <Tr>
            <Td>CSS</Td>
            <Td>言語</Td>
            <Td>業務で利用した</Td>
          </Tr>
          <Tr>
            <Td>C</Td>
            <Td>言語</Td>
            <Td>趣味でやった・学生の時に学習した</Td>
          </Tr>
          <Tr>
            <Td>C++</Td>
            <Td>言語</Td>
            <Td>趣味でやった・学生の時に学習した</Td>
          </Tr>
          <Tr>
            <Td>Python</Td>
            <Td>言語</Td>
            <Td>趣味でやった・学生の時に学習した</Td>
          </Tr>
          <Tr>
            <Td>Golang</Td>
            <Td>言語</Td>
            <Td>業務で利用した</Td>
          </Tr>
          <Tr>
            <Td>CodeIgniter</Td>
            <Td>フレームワーク</Td>
            <Td>業務で利用した</Td>
          </Tr>
          <Tr>
            <Td>Laravel</Td>
            <Td>フレームワーク</Td>
            <Td>業務で利用した</Td>
          </Tr>
          <Tr>
            <Td>Nuxt.js</Td>
            <Td>フレームワーク</Td>
            <Td>趣味でやった・学生の時に学習した</Td>
          </Tr>
          <Tr>
            <Td>Serverless Framework</Td>
            <Td>フレームワーク</Td>
            <Td>趣味でやった・学生の時に学習した</Td>
          </Tr>
          <Tr>
            <Td>Vue.js</Td>
            <Td>フレームワーク</Td>
            <Td>趣味でやった・学生の時に学習した</Td>
          </Tr>
          <Tr>
            <Td>Gridsome</Td>
            <Td>フレームワーク</Td>
            <Td>趣味でやった・学生の時に学習した</Td>
          </Tr>
          <Tr>
            <Td>Gin</Td>
            <Td>フレームワーク</Td>
            <Td>業務で利用した</Td>
          </Tr>
          <Tr>
            <Td>React</Td>
            <Td>フレームワーク</Td>
            <Td>業務で利用した</Td>
          </Tr>
          <Tr>
            <Td>Next.js</Td>
            <Td>フレームワーク</Td>
            <Td>業務で利用した</Td>
          </Tr>
          <Tr>
            <Td>Bootstrap</Td>
            <Td>ライブラリ</Td>
            <Td>業務で利用した</Td>
          </Tr>
          <Tr>
            <Td>jQuery</Td>
            <Td>ライブラリ</Td>
            <Td>業務で利用した</Td>
          </Tr>
          <Tr>
            <Td>PostgreSQL</Td>
            <Td>DB</Td>
            <Td>業務で利用した</Td>
          </Tr>
          <Tr>
            <Td>MySQL</Td>
            <Td>DB</Td>
            <Td>趣味でやった・学生の時に学習した</Td>
          </Tr>
          <Tr>
            <Td>MongoDB</Td>
            <Td>DB</Td>
            <Td>業務で利用した</Td>
          </Tr>
          <Tr>
            <Td>Github</Td>
            <Td>ソースコード管理</Td>
            <Td>業務で利用した</Td>
          </Tr>
          <Tr>
            <Td>Gitlab</Td>
            <Td>ソースコード管理</Td>
            <Td>業務で利用した</Td>
          </Tr>
          <Tr>
            <Td>AWS</Td>
            <Td>インフラ</Td>
            <Td>業務で利用した</Td>
          </Tr>
          <Tr>
            <Td>GCP</Td>
            <Td>インフラ</Td>
            <Td>趣味でやった・学生の時に学習した</Td>
          </Tr>
          <Tr>
            <Td>gRPC</Td>
            <Td>API</Td>
            <Td>業務で利用した</Td>
          </Tr>
          <Tr>
            <Td>GraphQL</Td>
            <Td>API</Td>
            <Td>業務で利用した</Td>
          </Tr>
          <Tr>
            <Td>GORM</Td>
            <Td>ライブラリ</Td>
            <Td>業務で利用した</Td>
          </Tr>
          <Tr>
            <Td>SQLBoiler</Td>
            <Td>ライブラリ</Td>
            <Td>趣味でやった・学生の時に学習した</Td>
          </Tr>
        </Tbody>
      </Table>
    </ContentsContainer>
  );
};

export default SkillStacks;
