import React from "react";

const SkillStacks = () => {
  return (
    <div>
      <h2>スキルスタック</h2>
      <table>
        <thead>
          <tr>
            <th>スキル</th>
            <th>カテゴリ</th>
            <th>熟練度</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>PHP</td>
            <td>言語</td>
            <td>業務で利用した</td>
          </tr>
          <tr>
            <td>TypeScript</td>
            <td>言語</td>
            <td>業務で利用した</td>
          </tr>
          <tr>
            <td>JavaScript</td>
            <td>言語</td>
            <td>業務で利用した</td>
          </tr>
          <tr>
            <td>Java</td>
            <td>言語</td>
            <td>業務で利用した</td>
          </tr>
          <tr>
            <td>GAS</td>
            <td>言語</td>
            <td>業務で利用した</td>
          </tr>
          <tr>
            <td>HTML</td>
            <td>言語</td>
            <td>業務で利用した</td>
          </tr>
          <tr>
            <td>CSS</td>
            <td>言語</td>
            <td>業務で利用した</td>
          </tr>
          <tr>
            <td>C</td>
            <td>言語</td>
            <td>趣味でやった・学生の時に学習した</td>
          </tr>
          <tr>
            <td>C++</td>
            <td>言語</td>
            <td>趣味でやった・学生の時に学習した</td>
          </tr>
          <tr>
            <td>Python</td>
            <td>言語</td>
            <td>趣味でやった・学生の時に学習した</td>
          </tr>
          <tr>
            <td>Golang</td>
            <td>言語</td>
            <td>業務で利用した</td>
          </tr>
          <tr>
            <td>CodeIgniter</td>
            <td>フレームワーク</td>
            <td>業務で利用した</td>
          </tr>
          <tr>
            <td>Laravel</td>
            <td>フレームワーク</td>
            <td>業務で利用した</td>
          </tr>
          <tr>
            <td>Nuxt.js</td>
            <td>フレームワーク</td>
            <td>趣味でやった・学生の時に学習した</td>
          </tr>
          <tr>
            <td>Serverless Framework</td>
            <td>フレームワーク</td>
            <td>趣味でやった・学生の時に学習した</td>
          </tr>
          <tr>
            <td>Vue.js</td>
            <td>フレームワーク</td>
            <td>趣味でやった・学生の時に学習した</td>
          </tr>
          <tr>
            <td>Gridsome</td>
            <td>フレームワーク</td>
            <td>趣味でやった・学生の時に学習した</td>
          </tr>
          <tr>
            <td>Gin</td>
            <td>フレームワーク</td>
            <td>業務で利用した</td>
          </tr>
          <tr>
            <td>React</td>
            <td>フレームワーク</td>
            <td>業務で利用した</td>
          </tr>
          <tr>
            <td>Next.js</td>
            <td>フレームワーク</td>
            <td>業務で利用した</td>
          </tr>
          <tr>
            <td>Bootstrap</td>
            <td>ライブラリ</td>
            <td>業務で利用した</td>
          </tr>
          <tr>
            <td>jQuery</td>
            <td>ライブラリ</td>
            <td>業務で利用した</td>
          </tr>
          <tr>
            <td>PostgreSQL</td>
            <td>DB</td>
            <td>業務で利用した</td>
          </tr>
          <tr>
            <td>MySQL</td>
            <td>DB</td>
            <td>趣味でやった・学生の時に学習した</td>
          </tr>
          <tr>
            <td>MongoDB</td>
            <td>DB</td>
            <td>業務で利用した</td>
          </tr>
          <tr>
            <td>Github</td>
            <td>ソースコード管理</td>
            <td>業務で利用した</td>
          </tr>
          <tr>
            <td>Gitlab</td>
            <td>ソースコード管理</td>
            <td>業務で利用した</td>
          </tr>
          <tr>
            <td>AWS</td>
            <td>インフラ</td>
            <td>業務で利用した</td>
          </tr>
          <tr>
            <td>GCP</td>
            <td>インフラ</td>
            <td>趣味でやった・学生の時に学習した</td>
          </tr>
          <tr>
            <td>gRPC</td>
            <td>API</td>
            <td>業務で利用した</td>
          </tr>
          <tr>
            <td>GraphQL</td>
            <td>API</td>
            <td>業務で利用した</td>
          </tr>
          <tr>
            <td>GORM</td>
            <td>ライブラリ</td>
            <td>業務で利用した</td>
          </tr>
          <tr>
            <td>SQLBoiler</td>
            <td>ライブラリ</td>
            <td>趣味でやった・学生の時に学習した</td>
          </tr>
        </tbody>
      </table>
    </div>
  );
};

export default SkillStacks;
